Force download of file regardless of type
bitwarden/web pull request #1038
Opened 2021-06-17 00:06 UTC by OJ

The file download feature in Bitwarden Send currently treats PDF files as a special case by not forcing the file to be downloaded. By the looks of it the reasoning is to make use of the built-in PDF viewer that comes with the browser.

Based on my use of the application, and our extensive sharing of PDFs with non-technical people, this special case is a genuine usability problem. Almost every person we have shared a PDF document with has thought that the download feature hasn't worked because of the built-in popup blocker.

The code in question makes an exemption for Safari, so it's not an issue in that case, but for every other browser this is proving to be a concern.

From a usability point of view, I do not think that PDF files should be treated any differently. When a user clicks a link that says "Download File", they would expect a file to be downloaded. That's certainly what I would expect. I also personally dislike it when applications try to be too smart in cases like this and try to use built-in browser features for certain file types.

Attempting to download a file in Bitwarden Send should result in the file being downloaded. If the user has their browser configured to view PDF files, then that's what will happen when they try to open it. If they do not, then their other chosen viewer will be invoked. This option is still under the control of the user even when the file has been downloaded first.

This small change removes the code that treats PDF files as a special case. Instead the files are downloaded directly just like any other file type. This consistency is a win for useability and avoids the problem of popup blocker getting in the way of downloading PDF files.

I checked to see where else in the code this download feature is used and found the following:

```
./src/app/settings/user-subscription.component.ts:        this.platformUtilsService.saveFile(window, licenseString, null, 'bitwarden_premium_license.json');
./src/app/organizations/manage/events.component.ts:        this.platformUtilsService.saveFile(window, data, { type: 'text/plain' }, fileName);
./src/app/organizations/settings/download-license.component.ts:            this.platformUtilsService.saveFile(window, licenseString, null, 'bitwarden_organization_license.json');
```

The above cases are all non-PDF files, so the change does not impact them at all.

I'm sure there were good reasons for putting this feature in place to begin with. I just feel that treating any file as a special case is a bad idea, removes control from the user and results in unexpected behaviour. It's especially bad when downloads just don't work because popups are silently blocked.

I welcome any discussion on the topic. Thanks very much for your time.

2021-06-17 00:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/web?pullRequest=1038) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/web?pullRequest=1038) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/web?pullRequest=1038) it.</sub>

2021-06-21 16:28 UTC, cscharf commented
See: https://github.com/bitwarden/web/pull/888 for background/reference regarding the Safari issue. As far as functionality goes, I tend to agree that a download should be kept a download. I don't remember if there was explicit browser behavior issues with setting one way or the other given Safari and the blob data technique used to prompt the file download. Assigning to @MGibson1 for when he has time to do a quick review.

Asana Ref: https://app.asana.com/0/1169444489336079/1200050082951941/f

2021-06-30 13:03 UTC, MGibson1 requested changes
@OJ, Thanks for taking this on. You aren't _quite_ correct that this has no other implications beyond Send. This same method is used to download attachments from Cipher items. I don't think we want to change the download/open behavior there, but we agree that the behavior _should_ change for send.

So, I think the way to handle this is to change the method signature of `saveFile` to include an option to `forceDownload`, which will default false, but we'll set to true for the Send `access` page.

2021-07-04 13:18 UTC, OJ commented
I didn't see any other refs in the code outside of send other than the ones shown above and they all seem to force a content type that isn't PDF. Would you mind pointing me at where I missed it?

Thank you!

2021-07-05 16:28 UTC, MGibson1 commented
Sure, it's here: https://github.com/bitwarden/jslib/blob/master/angular/src/components/attachments.component.ts#L149, in the [jslib](bitwarden/jslib) repository.

2022-06-02 20:37 UTC, closed without merging