Use 2fa.directory API v3 in inactive 2FA report
bitwarden/web pull request #1103
Opened 2021-07-29 13:51 UTC by ApCoder123

https://community.bitwarden.com/t/improve-inactive-2fa-report/32045

Closes #982

2021-07-29 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/web?pullRequest=1103) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/web?pullRequest=1103) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/web?pullRequest=1103) it.</sub>

2021-08-29 12:52 UTC, djsmith85 commented
Hi @ApCoder123 Thank you for your contribution. 

I've just tested this and although it does solve the above mentioned issue, it misses other domains which should pop up. I used for example `https://www.avanza.se/` and `netcup.de`. With the original version I would get a hit for `avanza` but with your version it would not show up. If I remove the `http://` from the URI-input it would show up. 

If you are still willing to spend some more time on this, could you please do some more testing and make sure that all entries show up.

Kind Regards,
Daniel

2021-08-29 12:54 UTC, djsmith85 requested changes
Hi @ApCoder123 Thank you for your contribution. 

I've just tested this and although it does solve the above mentioned issue, it misses other domains which should pop up. I used for example `https://www.avanza.se/` and `netcup.de`. With the original version I would get a hit for `avanza` but with your version it would not show up. If I remove the `http://` from the URI-input it would show up. 

If you are still willing to spend some more time on this, could you please do some more testing and make sure that all entries show up.

Kind Regards,
Daniel

2021-09-02 18:59 UTC, ApCoder123 commented
Ok, I've made some changes now which should resolve these issues. Rather than just test the hostname, I have modified it to check the base domain (should close #893 as well), which should resolve these issues. 

I believe the reason for `https://www.avanza.se` not showing up was because when the `url` field was being grabbed from the v2 API, `Utils.getHostname()` would cause `www.avanza.se` to be added to the services map, however when the v3 API provides just the domain, `www.avanza.se` wouldn't match `avanza.se`, causing it not to be shown. The checking of the main domain in the `setCiphers()` function should resolve this now.

2021-10-03 16:54 UTC, ApCoder123 commented
Hi @djsmith85
Sorry to bother you, but are there any updates on when this might be able to be merged? Thanks

2021-11-15 10:08 UTC, djsmith85 requested changes
Hi @ApCoder123 I'm really sorry it has taken me so long to get back to you. 

I've had another look at this and based on the data we are retrieving I think we can get rid of the insertation and comparison with hostnames. If we only include the domain, which is present on every item from 2fa-directory json, we could only check for that in the setCiphers method.

After retrieving the domain from the cipher's uri, we should remove the `www.` (replace).

For the loop in `load2fa` could you please invert the `if's` and use `continue`, to reduce if-nesting.

2021-11-16 08:35 UTC, djsmith85 requested changes
@ApCoder123 Only requesting some minor styling changes and then this is looking good. Thank you again for being so patient

2021-11-16 08:35 UTC, djsmith85 commented on src/app/tools/inactive-two-factor-report.component.ts
> +                        const uri = u.uri.replace("www", "");
This should be using single-quotes.

2021-11-16 08:35 UTC, djsmith85 commented on src/app/tools/inactive-two-factor-report.component.ts
> +            if (serviceData.documentation == null) continue;
Please add curly braces, for one-liner if-statements

2021-11-16 16:31 UTC, djsmith85 requested changes

2021-11-16 16:31 UTC, djsmith85 commented on src/app/tools/inactive-two-factor-report.component.ts
> +                        const uri = u.uri.replace('www', '');
Missing a dot, should be `www.`

2021-11-16 16:31 UTC, djsmith85 commented on src/app/tools/inactive-two-factor-report.component.ts
> +            if (serviceData.documentation == null) { continue }
Please add line breaks, we don't use single-line if's and also semicolons after the `continue`s

2021-11-16 17:33 UTC, djsmith85 approved these changes
@ApCoder123 This is looking good now. Thank you very much for your time and patience.
Placing a `hold` label as we're gearing up to cut our release-candidate branches this week, will merge after that.

2021-11-24 15:25 UTC, merged