Add credit card logos to allow displaying icons based on brand
bitwarden/web pull request #1280
Opened 2021-11-08 10:32 UTC by linusaarnio

This is PR 4/4 related to https://community.bitwarden.com/t/credit-card-logos-for-card-vault-items/33267

## Type of change
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Add images for the credit card logos.

## Code changes
This PR adds the images needed by https://github.com/bitwarden/jslib/pull/537.
They are a modified (changed size to look better in the 20x20 box for icons) version of https://www.figma.com/community/file/880472656109554171 which is licenced under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) by Arthur Chayka

## Screenshots

![web](https://user-images.githubusercontent.com/42450444/140726726-e96066a0-69ad-4b9c-910d-48a676708dfd.png)

## Testing requirements
Test that images are shown correctly for the different brands.
Test that no brands are shown when "Disable Website Icons" is checked in options.

## Before you submit
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2021-11-09 20:25 UTC, Hinton commented
@linusaarnio The icon license requires a bit of consideration, will have to check internally how to provide the required attribution or if there are alternative icons we can use instead.

2021-11-10 13:00 UTC, linusaarnio commented
@Hinton Yes it does, forgot to write about that. It is up to you how you choose to add attribution, my suggestion would be to add it in the "About" part of settings in the respective clients.

2021-11-22 22:48 UTC, danielleflinn commented
Hi @linusaarnio, thank you for your patience while we reviewed your PR. We have developed a set of icons that does not require attribution that we'd like to use for this project. See the attached zip file for compressed pngs. 

There is a light and dark version of each icon that should be used with the corresponding themes. 

The images should be sized to not stretch when used; but let me know if there are any issues when you swap out with the icons you currently have. Thanks for your contribution!

[tinified.zip](https://github.com/bitwarden/web/files/7584807/tinified.zip)

2021-11-23 15:17 UTC, linusaarnio commented
Thank you @danielleflinn, the icons look great!

Should the dark theme icons be used for all themes except for default/light one ( i.e. solarized dark and nord)?

2021-12-02 14:04 UTC, linusaarnio commented
@danielleflinn I have done the switch as I suggested in my earlier comment, with the themes Solarized dark and Nord (in the clients that have these themes) using the dark version of the icons since it seemed like the most logical option. Let me know if this should be changed.

Also, the American Express icon looks like the text is shifted a bit to the right. Is this intentional?

2021-12-09 10:17 UTC, Hinton commented
@danielleflinn It seems that discovery light is slightly bigger than the other icons. Should we update it to be consistent?

@linusaarnio I wonder slightly if we should put the icons and css in jslib to avoid duplicating them across our projects.

2021-12-09 16:34 UTC, Hinton commented
@linusaarnio we've updated the icons to have a bit better resolution. (24 x 19)

[payment-icons.zip](https://github.com/bitwarden/web/files/7686852/payment-icons.zip)

2021-12-16 14:27 UTC, Hinton requested changes
Once jslib is merged, we'll need to update the jslib submodule.

2021-12-16 14:27 UTC, Hinton commented on src/scss/styles.scss
> +$dark-icon-themes: 'theme_dark';
I think we could move this to variables.

2021-12-16 14:27 UTC, Hinton commented on src/scss/styles.scss
> +@import "../../jslib/angular/src/scss/icons.scss";
And this needs to be placed below fontawesome, since we override one of the css properties.

2021-12-21 11:05 UTC, djsmith85 approved these changes
This is looking good. @linusaarnio Nice work!

2021-12-21 11:07 UTC, Hinton approved these changes

2021-12-21 11:08 UTC, merged

2021-12-21 11:08 UTC, Hinton commented
Thanks for the contribution @linusaarnio.