[Bug] Fix select options background color (#1338)
bitwarden/web pull request #1351
Opened 2021-12-17 19:55 UTC by GiacomoPignoni

## Type of change

- [x ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Fix for bug #1338 

## Code changes
- forms.scss
Added background color from theme, to <option> tag in a form-control class

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/34923063/146600523-1cb2e880-a8d7-455a-bed5-9c8c90391a81.png)

## Testing requirements

Check if in dark mode the select options input have dark background

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2021-12-17 19:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/web?pullRequest=1351) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/web?pullRequest=1351) before we can accept your contribution.<br/><hr/>**Giacomo Pignoni** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/web?pullRequest=1351) it.</sub>

2021-12-19 12:00 UTC, djsmith85 requested changes
@GiacomoPignoni Thank you for your contribution. Please sign the CLA so we can use your contribution. 

The changes look good. The merge conflicts are highly likely because we added and applied `prettier` to our codebase. Instructions on how to resolve these can be found here: https://github.com/bitwarden/web#prettier

2021-12-29 00:53 UTC, maroy1986 commented
I was going to do the exact same PR and then I saw this one. If this PR never gets completed because he can't sign the CLA, let me know and I'll do it! :)

2022-01-25 17:18 UTC, leobaldoneto commented
Any news? An simple fix, but it's stucked because license agreement.

2022-01-26 04:56 UTC, eliykat commented
Fixed by https://github.com/bitwarden/web/pull/1255, thanks all.

2022-01-26 04:56 UTC, closed without merging