[End User Vault Refresh] Vault page
bitwarden/web pull request #1529
Opened 2022-03-09 04:17 UTC by eliykat

## Type of change

- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Testing requirements

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-03-17 11:49 UTC, Hinton requested changes

2022-03-17 11:49 UTC, Hinton commented on src/app/providers/providers.component.html
> +<ng-container>
Should be safe to remove this ng-container now as well right?

2022-03-17 11:49 UTC, Hinton commented on src/app/settings/organizations.component.html
> +<ng-container>
Same, can we remove this container?

2022-03-17 23:11 UTC, eliykat commented
All the alignment changes messed up the diff, make sure you hide whitespace changes.

2022-03-22 09:55 UTC, Hinton approved these changes

2022-03-22 20:32 UTC, merged