add username generation to generator
bitwarden/web pull request #1566
Opened 2022-03-25 18:56 UTC by kspearrin

## Type of change

- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Add support for username generation.

Asana task: https://app.asana.com/0/1200578627114106/1201532987437763

## Code changes

- Add new translations
- Implement UI changes to accommodate username generation on the generator page (see screenshots below)

## Screenshots

![image](https://user-images.githubusercontent.com/1190944/160184170-8b05c6ab-bfd2-4f80-b1e0-d38ee6505da9.png)

![image](https://user-images.githubusercontent.com/1190944/160184210-1aef571a-22e1-4c6d-ba99-5eeeffe4ca47.png)

![image](https://user-images.githubusercontent.com/1190944/160184249-cbaea723-3fcf-4451-861b-5edafcf8195e.png)

## Testing requirements

1. Test existing password generation options from generator.
2. Test new username generation options from generator.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [x] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-03-28 04:36 UTC, eliykat requested changes

2022-03-28 04:36 UTC, eliykat commented on src/app/tools/password-generator.component.html
> +<div class="d-flex" *ngIf="type === 'password'">
You can roll this into the `<ng-container>` for password generation.

2022-03-28 04:36 UTC, eliykat commented on src/app/tools/password-generator.component.html
> +<div *ngIf="type === 'username'">
Same here, move into the `<ng-container>` for username generation.

2022-03-28 04:51 UTC, eliykat reviewed
In the desktop PR you added a "generate" action button next to the username field in `add-edit-component`. Can we do the same here?

2022-03-28 14:12 UTC, kspearrin commented
> In the desktop PR you added a "generate" action button next to the username field in `add-edit-component`. Can we do the same here?

We don't have the concept of opening a dedicated generator view in the web vault. For password we just generate a password based on your last settings. I am not sure that will be sufficient enough for a username generator where you probably need to adjust the settings to the website more frequently.

2022-03-29 01:42 UTC, eliykat approved these changes

2022-03-29 19:02 UTC, merged