[GDPR] Adjusted TOC/Privacy acceptance
bitwarden/web pull request #684
Opened 2020-10-29 14:59 UTC by vincentsalucci

## Objective
> In order to complete GDPR compliance, moving forward with new user creation, we need to have explicit user interaction for Terms of Service and Privacy Policy acknowledgement.

## Code Changes
- **register.component.html**: Removed old acceptance views. Added new checkbox and label elements. Styled similarly to other helper text within this component. 
- **register.component.ts**: Added tracking boolean for new checkbox. Adjusted `submit` logic to include a check for policies acceptance.
- **messages.json**: Added label message and error message for policy acceptance.

2020-10-29 15:51 UTC, cscharf reviewed
Just one minor formatting nit. Also added GO to review verbiage and final fit/finish.

2020-10-29 15:51 UTC, cscharf commented on src/app/accounts/register.component.html
>                                  few months, I can see why." - February 2020
move this line up for continuity in code style.

2020-10-29 15:51 UTC, go12 approved these changes

2020-10-29 18:41 UTC, kspearrin requested changes

2020-10-29 18:41 UTC, kspearrin commented on src/app/accounts/register.component.html
> -                                    {{'submitAgreePolicies' | i18n}}
remove this old string?

2020-11-01 20:01 UTC, vincentsalucci commented on src/app/accounts/register.component.html
> -                                    {{'submitAgreePolicies' | i18n}}
Removed!

2020-11-02 18:44 UTC, kspearrin submitted a review, later dismissed

2020-11-02 20:24 UTC, kspearrin approved these changes

2020-11-02 22:33 UTC, merged